# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

In [1]:
#Import it as library
import numpy as np

Numpy has many built-in functions and capabilities. 
Some of the most important aspects of Numpy:
- vectors
- arrays
- matrices
- number generation.

# Numpy Arrays: vectors and matrices
- vectors: 1-d arrays
- matrices: 2-d (but you should note a matrix can still have only one row or one column)


Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

## From a Python List
- np.arrary(list)
We can create an array by directly converting a list or list of lists:

## built-in method
### arrange: 
Return evenly spaced values within a given interval.
- np.arange(start, end, stepsize) e.g., np.arange(0, 10) gives you arrary from 0 to 9
    - step size = 间隔
    - end (exclusive)
-np.arange(n): 0~n-1


### zeros and ones
Generate arrays of zeros or ones

- np.zeros(#),   np.zeros((row, col)) gives u row*col 0 matrix
- np.ones9(#)


### linspace
Return evenly spaced numbers over a specified interval.
- np.linspace(start,end, # in the interval)

### eye
Creates an identity matrix
- np.eye(n): n rows of identity matrix


### rand
Numpy also has lots of ways to create random number arrays
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.
- np.random.rand(x): gives you an array of x number that is uniformly distributed

### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:
- np.random.randn(x): gives you x number that is standard normal distributed


### randint
Return random integers from `low` (inclusive) to `high` (exclusive).
- np.random.randint(low, high, #): return # of int in the range log~high-1


### shortcut of np.random
from numpy.random import randint

randint(x,y)


## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

### Reshape
Returns an array containing the same data with a new shape.
- arr.reshape(row, col): rehsape into a row*col matrix
    - row*col = actual number in the array you want to reshape
    
### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax
- arr.min()
- arr.max()
- arr.argmax(): return index of max value
- arr.argmin(): return inex of min value

### Array ATTRIBUTES
### shape
- it is an attribute that array has, not method, so no parenthesis 
- arr.shape: gies you dimension of array
    - (25,): means 25*1
    
### dypes
You can also grab the data type of the object in the array
- arr.dtype

# NumPy Indexing and Selection

How to select elements or groups of elements from an array.

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:
- arr[index]: returns the value at index, remember arr starts from 0 
- arr[low, high]: reutrn value in a range, low ~ high -1
- arr[: high]: return everyting up to index high (exclusive)
- arr[low:]: return evrything from index low (inclusive)


## Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:
- arr[low:high] = value: Setting a value with index range
    - assign a value to slice of arrary will also change the original value in array!
    - Data is not copied, it's a view of the original array! This avoids memory problems! (avoid large array in memory)
    - if you want to copy: use arr.copy()

## Indexing a 2D array (matrices)
The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.
- arr[row][col] 
- arr[row, col]   recommended!
- slice 2d array: arr[:high, low;] - slice row up to high, column from low
- multiple row: arr[[2,4]]


### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order
- make every row's value = it's row number


## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.
- bool = arr + comparison: returns an array of boolean after compare
- arr[bool]: gives you value that is true for comparison
Use them in one step to select elements that satisfy condition in an array
- arr[arr+cond]: return value in the array that satisfy condition

# NumPy Operations
- Arry with Array
- Array with Scalars
- Universal Array Functions

## Arithmetic
You can easily perform array with array arithmetic, or scalar with array arithmetic. 
- Arry with Array
- Array with Scalars
    - note: 1/0 divide 0, you will get ZeroDivisionError
    - array/0 elements, you will get warning, and replaced with nan or inf
- Universal Array Functions: Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array
    - np.sqrt(arr)
    - np.exp(
    - np.max(arr) = arr.max()
    - np.exp(arr)
    - np.sin(arr)
    - np.log(arr)
    - np.sum(arr)
    - arr.sum(axix=0/1): 0 indicates column, 1 indicates row

  


In [19]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,50, 10)
ranarr

array([41, 47, 42, 14, 17,  0, 24, 23, 41,  2])

In [25]:
#reshape into new dimension
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
#Convert a list into arrary
arr = np.array(my_list)

In [8]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(0,5, 10)

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.72793022, 0.43407572, 0.96066537, 0.85184498, 0.13225885])

In [46]:
arr_2d = np.array([[1,2,3], [2,3,4], [3,4,5]])
arr_2d[0]

array([1, 2, 3])

In [50]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
bool_arr = arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [52]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [54]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [57]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr+arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
arr /arr

/Users/apple/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
1/arr

/Users/apple/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [64]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [70]:
np.log(arr)

/Users/apple/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])